*** Variables ***
${checkBox_enable_sms_broadcast_receiver}    //android.widget.CheckBox[@content-desc="Enable SMS broadcast receiver"]
${txt_recipient}    //android.widget.EditText[@resource-id="io.appium.android.apis:id/sms_recipient"]
${txt_messageBody}    //android.widget.EditText[@resource-id="io.appium.android.apis:id/sms_content"]
${btn_send}    //android.widget.Button[@content-desc="Send"]

*** Keywords ***