*** Variables ***
${preference_from_xml}    //android.widget.TextView[@content-desc="1. Preferences from XML"]
${launching_preference}    //android.widget.TextView[@content-desc="2. Launching preferences"]
${preference_dependencies}    //android.widget.TextView[@content-desc="3. Preference dependencies"]
${default_values}    //android.widget.TextView[@content-desc="4. Default values"]
${preferences_from_code}    //android.widget.TextView[@content-desc="5. Preferences from code"]
${advanced_preference}    //android.widget.TextView[@content-desc="6. Advanced preferences"]
${switch}    //android.widget.TextView[@content-desc="9. Switch"]

*** Keywords ***