name: Test env

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - '*.md'
  workflow_dispatch:

jobs:
  test_env:
    env:
      CI: true
      PLATFORM_NAME: Android
      PLATFORM_VERSION: ${{ matrix.androidVer }}
      DEVICE_NAME: emulator-5554
      APP_PACKAGE: io.appium.android.apis
      APP_ACTIVITY: io.appium.android.apis.ApiDemos
      AUTOMATION_NAME: uiautomator2
      PATH_TO_APK: ${{ github.workspace }}/apks/ApiDemos_debug.apk
      APK_LINK: ${{ secrets.APK_LINK }}
      ANDROID_AVD: emulator
      APPIUM_TEST_SERVER_PORT: 4567
      APPIUM_TEST_SERVER_HOST: 127.0.0.1
      _FORCE_LOGS: 1
      TEST_PASS_THRESHOLD: 10

    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: test env
        run: |
          echo ${{ env.APK_LINK }}

      - name: run script
        run: |
          bash -xe scripts/run-functional-tests.sh